### ISSUE TITLE
Is RS232 to TTL adapter needed when I do not utilize ACIO mode?

### ISSUE THREAD

**Issue by exponent96** [CrazyRedMachine/NostalgiaIO#1]
Hello.

I'm planning to use the arcade PCB as PC controller.
So, I'm collecting the parts that I need, but is the adapter necessary?
I've read the readme text, but I understood that the adapter is needed for the connection with acio device only.
In fact it is totally okay to buy an adapter (or a shield, because it is cheap), but I'm just curious what exactly this adapter does in your software.

**Comment by CrazyRedMachine** [comment]
hi, yes it is always necessary

the piano itself is an acio device. it uses rs232 communication. arduino doesn't do rs232 so you need the adapter to be able to communicate with the piano

**Comment by exponent96** [comment]
Got it. In fact I already have bought one, so it is completely okay to use it.
Thank you! I'll try to use it!
