### ISSUE TITLE
Software solution for cabinets

### ISSUE THREAD

**Issue by Grumbledor** [CrazyRedMachine/NostalgiaIO#2]
I'm curious if a software solution is available so that I could run win10 and Nostalgia PC on the BemaniPC in my Cabinet.   I'm trying to get around having to make any changes other than swapping HDs to go between AC and PC data.

**Comment by CrazyRedMachine** [comment]
you might want to check bemanitools repo, I wrote an handler for aciotest which reads from the keyboard... that's half the work done.

the other half is to adapt the handler code so that it sends midi signals to a midi loopback adapter (or virtual keyboard presses like popnforwarder if you're lazy lol)

**Comment by Grumbledor** [comment]
I took a look at the code and it's 100% Greek to me.  I'm fairly certain I found the right handler but I just don't understand how or why the code works.   That said,  If this isn't a hard thing to put together  I'd certainly be willing to pay you for your time.

**Comment by Grumbledor** [comment]
Abandoned software and just went with hardware solution

**Comment by CrazyRedMachine** [comment]
i'll eventually write a software thing, i'm unfortunately busy with other projects for now. hardware solution still has native passthrough so it still conveniently fits your usecase

**Comment by Grumbledor** [comment]
I am having an absolute bear of a time getting the native passthru on this to work.  I've got it working just fine for pc data in midi mode,  but when I try to switch back to acc data I get a keyboard error.   I've thrown everything I've got at this.  Do you think you could reach out to me via discord?  .

**Comment by CrazyRedMachine** [comment]
(software solution sent via discord, waiting for confirmation it's working well on cab hardware then i'll update the repo)
